<?php

    $apikey = "rzp_test_LnA3aQsfLID6Y2";
    $o_id='OID'.rand(100000000,9999999999).'END';
    $amout= $_POST['amount'];

    $currentDate = date('Y-m-d');

    $address=$_POST['address'];
    $district=$_POST['district'];
    $pincode=$_POST['pincode'];
    $phone=$_POST['phone'];
?>

<form action="test.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amout*100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo $oid; ?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Online Pharmacy and Deleivery System"
    data-description="Online pharmacy and medicine delivery system"
    data-image="https://img.freepik.com/free-vector/flat-design-medical-pharmacy-symbol_23-2149542039.jpg"
    data-prefill.name="<?php echo $_POST['fullname'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.contact="<?php echo $_POST['phone'];?>"

    data-theme.color="#F37254"
></script>

    <input type="hidden" name='fullname' value="<?php echo $_POST['fullname'];?>">
    <input type="hidden" name='date' value="<?php echo $currentDate;?>">
    <input type="hidden" name='o_id' value="<?php echo $o_id;?>">
    <input type="hidden" name='amount' value="<?php echo $amout;?>">

    <input type="hidden" name='address' value="<?php echo $address;?>">
    <input type="hidden" name='district' value="<?php echo $district;?>">
    <input type="hidden" name='pincode' value="<?php echo $pincode;?>">
    <input type="hidden" name='phone' value="<?php echo $phone;?>">


<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>


